language: go

go:
  - master

install:
  - go get github.com/spf13/hugo

script:
  - hugo

deploy:
  local_dir: public
  repo: offtechnologies/offtechnologies.github.io
  target_branch: master
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
