baseURL = ""
languageCode = "en-us"
title = "Cloudbusting"
# theme = "hugo-theme-cactus-plus"
#useDescriptionReplaceSummary = true


[params]
	author = "offtechnologies"
	description = "Site Description"
	# bio = "author biography"



  iconFont = "font-awesome"
  socialIconStyle = ""

[social]

	github = "https://www.github.com/offtechnologies"
